version: 0.2

env:
  variables:
    SOLUTION: jenkins1.sln
    PACKAGE_DIRECTORY: packages
    DOTNET_FRAMEWORK: 4.7.2

phases:
  build:
    commands:
      - '& nuget restore'
      - '& msbuild /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:PackageAsSingleFile=false /p:Configuration=Release $env:SOLUTION'
artifacts:
  files:
    - bin\Debug\*
